### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an index

### ISSUE THREAD

**Issue by alior101** [cpury/lstm-math#1]
followed the readmy steps and got 

Using TensorFlow backend.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
lstm_1 (LSTM)                (None, 256)               276480    
_________________________________________________________________
dropout_1 (Dropout)          (None, 256)               0         
_________________________________________________________________
repeat_vector_1 (RepeatVecto (None, 7, 256)            0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 7, 256)            525312    
_________________________________________________________________
dropout_2 (Dropout)          (None, 7, 256)            0         
_________________________________________________________________
time_distributed_1 (TimeDist (None, 7, 13)             3341      
_________________________________________________________________
activation_1 (Activation)    (None, 7, 13)             0         
=================================================================
Total params: 805,133
Trainable params: 805,133
Non-trainable params: 0
_________________________________________________________________

Traceback (most recent call last):
  File "main.py", line 331, in <module>
    main()
  File "main.py", line 287, in main
    x_test, y_test, x_train, y_train = build_dataset()
  File "main.py", line 142, in build_dataset
    (n_test, MAX_EQUATION_LENGTH, N_FEATURES), dtype=np.bool
TypeError: 'float' object cannot be interpreted as an index

**Comment by cpury** [comment]
Are you on Python 2.x? It should work in Python 3.

**Comment by alior101** [comment]
oops. sorry..

**Comment by alior101** [comment]
this will fix the issue for people like me having multiple versions installed ..
virtualenv -p python3 venv; source venv/bin/activate

**Comment by cpury** [comment]
I'm glad it works for you now! I will mention the virtualenv thing in the blog post.
